# Generated by Django 3.1.4 on 2020-12-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
