# Generated by Django 3.1.4 on 2020-12-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0002_request_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='label',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
